### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by aferga77** [nftdevs/NFTs-Upload-to-OpenSea#109]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 241, in main_program_loop
  File "<string>", line 227, in wait_xpath
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Niklaus0001** [comment]
I am facing the same issue, if you find a solution pls let me know

**Comment by Nzent** [comment]
Same issue
![Screenshot 2022-03-14 160035](https://user-images.githubusercontent.com/26079832/158154614-3c5352f1-6b50-4e05-8065-40bfc85f879e.png)
