### ISSUE TITLE
it is not signing the metamask contract

### ISSUE THREAD

**Issue by DntIndustries** [nftdevs/NFTs-Upload-to-OpenSea#18]
Hi, a million thanks for this program 
today, for the current version of Chrome, the program is not signing the contract for selling the NFT. 
can you check it, please? 
Thanks again

**Comment by alexpardo1984** [comment]
please make sure you have the latest version of chromedriver (https://chromedriver.chromium.org/downloads) that works with the latest version of your chrome browser. I had the same issue but only had to manually sign the first one then it ran perfectly after that

**Comment by jpal3** [comment]
I updated the chrome driver manually and have signed three manually and each time I am left with this message: Traceback (most recent call last):
  File "C:\Users\_\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\_\Desktop\NFTs-Upload-to-OpenSea-nft\NFTs-Upload-to-OpenSea-nft\openseaupload.py", line 195, in main_program_loop
    sign.click()
  File "C:\Users\_\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\_\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\_\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\_\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="submit" class="Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb fzwDgL">...</button> is not clickable at point (280, 894). Other element would receive the click: <div aria-hidden="false" class="Overlayreact__Overlay-sc-1yn7g51-0 YLBvp">...</div>

**Comment by GeorgeGaming23** [comment]
Same here, i get the same problem of jpal3

**Comment by cloudmaking** [comment]
This may be of use...
https://github.com/cloudmaking/Auto_Chrome_2

**Comment by xl180500** [comment]
> 
IS the question be served？
