### ISSUE TITLE
error while starting code

### ISSUE THREAD

**Issue by ericmr1234** [nftdevs/NFTs-Upload-to-OpenSea#25]
when starting code, i recive the next error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Eric\Desktop\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 134, in main_program_loop
    driver.get(collection_link)
  File "C:\Users\Eric\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Eric\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Eric\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=96.0.4664.45)

i used the code for a few days, no errors were collected.

**Comment by llmontoryxd** [comment]
Same for me

**Comment by cloudmaking** [comment]
This may be of use...
https://github.com/cloudmaking/Auto_Chrome_2
