### ISSUE TITLE
Wont sign metamask

### ISSUE THREAD

**Issue by GeorgeGaming23** [nftdevs/NFTs-Upload-to-OpenSea#30]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\George Lopez\New folder\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\George Lopez\Pictures\nft\Progam for Selling\NFTs-Upload-to-OpenSea-main\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 142, in main_program_loop
    wait_xpath('//*[@id="media"]')
  File "C:\Users\George Lopez\Pictures\nft\Progam for Selling\NFTs-Upload-to-OpenSea-main\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 129, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\George Lopez\New folder\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by SidSarvesh** [comment]
im too getting the same kind of error code.

"selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="submit" class="Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb fzwDgL">...</button> is not clickable at point (239, 725). Other element would receive the click: <div data-testid="toasts" class="Blockreact__Block-sc-1xf18x6-0 Flexreact__Flex-sc-1twd32i-0 ToastsContainerreact__StyledContainer-sc-ihijgw-0 dBFmez jYqxGr kPAxwi"></div> (Session info: chrome=96.0.4664.110)"

**Comment by cloudmaking** [comment]
This may be of use...
https://github.com/cloudmaking/Auto_Chrome_2

**Comment by foxinnovs** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\BABA\Downloads\Compressed\NFTs-Upload-to-OpenSea-main\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 111, in main_program_loop
    driver = webdriver.Chrome(
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 98.0.4758.102

**Comment by cloudmaking** [comment]
Hi, you are using an older version of thia program, linked below is the most recent version
https://github.com/cloudmaking/Auto_Chrome_2
Sadly tho, the opensea bulk upload no longer works due to openseas captcha implementation.

Ali.

07519244960
@Cloudmaking
________________________________

**Comment by foxinnovs** [comment]
main_directory: C:\Users\BABA\Downloads\Auto_Chrome_2-main\Auto_Chrome_2-main
script_location: C:\Users\BABA\Downloads\Auto_Chrome_2-main\Auto_Chrome_2-main
if the above do not match the browser will not open
Contact @cloudmaking on twitter for support
Opening debug browser on port 8989
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\BABA\Downloads\Auto_Chrome_2-main\Auto_Chrome_2-main\Auto_Chrome_5.py", line 187, in main_program_loop
    driver = webdriver.Chrome(service=ser, options=op)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=98.0.4758.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x00707AC3+2587331]
        Ordinal0 [0x0069ADD1+2141649]
        Ordinal0 [0x00593BB8+1063864]
        Ordinal0 [0x00584077+999543]
        Ordinal0 [0x00594EF0+1068784]
        Ordinal0 [0x005DE16C+1368428]
        Ordinal0 [0x005DCD5A+1363290]
        Ordinal0 [0x005D84A6+1344678]
        Ordinal0 [0x005B53F6+1201142]
        Ordinal0 [0x005B62E6+1204966]
        GetHandleVerifier [0x008ADF22+1680738]
        GetHandleVerifier [0x00960DBC+2413564]
        GetHandleVerifier [0x0079D151+563089]
        GetHandleVerifier [0x0079BF13+558419]
        Ordinal0 [0x006A081E+2164766]
        Ordinal0 [0x006A5508+2184456]
        Ordinal0 [0x006A5650+2184784]
        Ordinal0 [0x006AF5BC+2225596]
        BaseThreadInitThunk [0x7677FA29+25]
        RtlGetAppContainerNamedObjectPath [0x771E7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x771E7A6E+238]

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\BABA\Downloads\Auto_Chrome_2-main\Auto_Chrome_2-main\Auto_Chrome_5.py", line 187, in main_program_loop
    driver = webdriver.Chrome(service=ser, options=op)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\BABA\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=98.0.4758.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x00707AC3+2587331]
        Ordinal0 [0x0069ADD1+2141649]
        Ordinal0 [0x00593BB8+1063864]
        Ordinal0 [0x00584077+999543]
        Ordinal0 [0x00594EF0+1068784]
        Ordinal0 [0x005DE16C+1368428]
        Ordinal0 [0x005DCD5A+1363290]
        Ordinal0 [0x005D84A6+1344678]
        Ordinal0 [0x005B53F6+1201142]
        Ordinal0 [0x005B62E6+1204966]
        GetHandleVerifier [0x008ADF22+1680738]
        GetHandleVerifier [0x00960DBC+2413564]
        GetHandleVerifier [0x0079D151+563089]
        GetHandleVerifier [0x0079BF13+558419]
        Ordinal0 [0x006A081E+2164766]
        Ordinal0 [0x006A5508+2184456]
        Ordinal0 [0x006A5650+2184784]
        Ordinal0 [0x006AF5BC+2225596]
        BaseThreadInitThunk [0x7677FA29+25]
        RtlGetAppContainerNamedObjectPath [0x771E7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x771E7A6E+238]

**Comment by cloudmaking** [comment]
Please dm me on twitter or Instagram for further support, with screenshots or videos and your operating system

Ali.

07519244960
@Cloudmaking
________________________________
