### ISSUE TITLE
Metamask sign

### ISSUE THREAD

**Issue by mateeej00** [nftdevs/NFTs-Upload-to-OpenSea#37]
At the end, I have to manually confirm (Sign) Metamask for each NFT loaded.
Loads everything automatically, but does not confirm Metamask automatically.

Does anyone have a solution?
Maybe the problem is the new version of Metamask? 

![NFT upload app](https://user-images.githubusercontent.com/96474310/147384355-85116c72-71d4-4d91-b44f-79013a4bd314.jpg)

**Comment by mateeej00** [comment]
This is from CMD:

![NFT upload app CMD](https://user-images.githubusercontent.com/96474310/147384508-998dab2d-4b23-4eef-942c-ee930d651942.jpg)

**Comment by SidSarvesh** [comment]
yes. I faced the same issue on my laptop. so I have changed my machine. 

I've decided to run this program on my old desktop and it's working fine. sometimes it will throw the same error. we have to re-run the program again to temporarily solve the issue. 
use a Different monitor or a different machine to cross-check it. 
it's a weird thing for me too. but it works.

I've uploaded almost 3000+ NFTs with this.

**Comment by tambenita** [comment]
I'm experiencing the same issue. I've tried three computers and different displays, though no change. May I ask, @sidsarvesh, what was the screen resolution for the computer that worked? Zoomed 100%? Chrome up to date (96)? Thanks!!

**Comment by mateeej00** [comment]
I managed to edit the software (openseaupload.py) so that it works for me now.

I am now loading NTFs up to 10000:
https://opensea.io/collection/rock-girls

Here is new software (file):
[openseaupload.py.zip](https://github.com/nftdevs/NFTs-Upload-to-OpenSea/files/7777685/openseaupload.py.zip)
***re-zip and change in your folder.

**Comment by bolobaos** [comment]
Thank you so much!!!!

**Comment by bolobaos** [comment]
It worked!!!! Thank you once again

**Comment by SidSarvesh** [comment]
> I managed to edit the software (openseaupload.py) so that it works for me now.
> 
> I am now loading NTFs up to 10000: https://opensea.io/collection/rock-girls
> 
> Here is new software (file): [openseaupload.py.zip](https://github.com/nftdevs/NFTs-Upload-to-OpenSea/files/7777685/openseaupload.py.zip) ***re-zip and change in your folder.

thank you for your effort. mention the author so he can check and update the code.

**Comment by SidSarvesh** [comment]
> It worked!!!! Thank you once again

great.

**Comment by mateeej00** [comment]
I delete this:

![Software_Delete](https://user-images.githubusercontent.com/96474310/147585594-4bc678cb-c2a4-4744-bc83-fb7d9d55a9f1.jpg)

**Comment by cloudmaking** [comment]
This may be of use...
https://github.com/cloudmaking/Auto_Chrome_2

**Comment by trrrd** [comment]
> This may be of use... https://github.com/cloudmaking/Auto_Chrome_2

and what may this be?

**Comment by trrrd** [comment]
I tried everything I saw here on how to fix the metamask sign problem but still not working
still showing:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\ifunanya orji fredri\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\ifunanya orji fredri\Desktop\my shop\NFT Collection\nft bulk upload\NFTs-Upload-to-OpenSea-main\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 193, in main_program_loop
  File "C:\Users\ifunanya orji fredri\Desktop\my shop\NFT Collection\nft bulk upload\NFTs-Upload-to-OpenSea-main\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 119, in wait_css_selector
    wait.until(
  File "C:\Users\ifunanya orji fredri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


somebody help ?

**Comment by cloudmaking** [comment]
> > This may be of use... https://github.com/cloudmaking/Auto_Chrome_2
> 
> and what may this be?

its the second version of the original script op based this script on, its a high level chrome automation tool... read the readme file... this script yu are using now is based on my original code which is outdated and not compatible with alot of stuff, i was nto credited ofcourse, if i was you all would know that i released and keep up to date a new version called auto_chrome_2, i have  ademo video in the readme file, cheeck it out if you want something which actually works.
