### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by Karmaismybtch** [nftdevs/NFTs-Upload-to-OpenSea#41]
The program just stops working after the first item is put on sale and just goess back to the beginning.

**Comment by Karmaismybtch** [comment]
Also I use formatic

**Comment by Karmaismybtch** [comment]
tart creating NFT SEALZ #1
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\RSK\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\RSK\Documents\Kady\ai\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 202, in main_program_loop
    driver.switch_to.window(login_page)
UnboundLocalError: local variable 'login_page' referenced before assignment

**Comment by Karmaismybtch** [comment]
It's not even creating items anymore
