### ISSUE TITLE
Metamask Sign (Ethereum Blockchain) cannot automatically click the sign Button

### ISSUE THREAD

**Issue by senosuke** [nftdevs/NFTs-Upload-to-OpenSea#43]
I have a problem with that, how to fix?

**Comment by Fr4nc3sc0O** [comment]
I have the same issue. Then it throws a timeout exception.

Start creating NFT CoRoNa Virus MuTanT #109
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1920, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\franc\OneDrive\Desktop\NFTs\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 193, in main_program_loop
    wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb fzwDgL']")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\OneDrive\Desktop\NFTs\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 119, in wait_css_selector
    wait.until(
    ^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.TimeoutException: Message:

**Comment by Fr4nc3sc0O** [comment]
I am using Windows 11.

**Comment by Fr4nc3sc0O** [comment]
This only happens on Ethereum. With Polygon as default everything works fine.
