### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by Drjacky** [nftdevs/NFTs-Upload-to-OpenSea#44]
```python
➜  NFTs-Upload-to-OpenSea git:(main) ✗ python openseaupload.py
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "openseaupload.py", line 71, in <module>
    collection_link_input = InputField("OpenSea Collection Link:", 2, 0, 1)
  File "openseaupload.py", line 58, in __init__
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

Also, I changed the chromedriver.exe with chromedriver for macOS

**Comment by nzbrian** [comment]
FileNotFoundError is only in Python3, not 2. Check you're using Python3
