### ISSUE TITLE
Can't sign polygon blockchain

### ISSUE THREAD

**Issue by Pouke1** [nftdevs/NFTs-Upload-to-OpenSea#52]
When it reaches Sell, it crashes
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\*****\Downloads\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 193, in main_program_loop
    wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb fzwDgL']")
  File "C:\Users\*****\Downloads\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 119, in wait_css_selector
    wait.until(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by CGJoe-code** [comment]
This will fix it

        wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
        sign = driver.find_element_by_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
        sign.click()
        time.sleep(2)

**Comment by erdiocalir** [comment]
> Bu düzeltecek
> 
> ```
>     wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
>     sign = driver.find_element_by_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
>     sign.click()
>     time.sleep(2)
> ```

the error he gave me after I wrote this :

C:\Users\Ocalir\Desktop\NFT YENİ\NFTs-Upload-to-OpenSea-nft\NFTs-Upload-to-OpenSea-nft>python openseaupload.py
  File "C:\Users\Ocalir\Desktop\NFT YENİ\NFTs-Upload-to-OpenSea-nft\NFTs-Upload-to-OpenSea-nft\openseaupload.py", line 198
    for handle in driver.window_handles:
IndentationError: unexpected indent

**Comment by iramalex11** [comment]
If you chose Polygon during the creation of the collection (before upload NFT's) is not necessary make the action of lines 160-168 because the polygon button is already chosen when you join the upload page. This is the solution:

`if is_polygon.get():
            blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]')
            blockchain_button.click()
            time.sleep(1)
            create = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button')
            driver.execute_script("arguments[0].click();", create)
            time.sleep(1)`

I stopped the code when it clicks on the blockchain button, but only makes a single click without changing to ethereum, and after this, it continues with the "create" button and keep working.

**Comment by iramalex11** [comment]
> If you chose Polygon during the creation of the collection (before upload NFT's) is not necessary make the action of lines 160-168 because the polygon button is already chosen when you join the upload page. This is the solution:
> 
> `if is_polygon.get(): blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]') blockchain_button.click() time.sleep(1) create = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button') driver.execute_script("arguments[0].click();", create) time.sleep(1)`
> 
> I stopped the code when it clicks on the blockchain button, but only makes a single click without changing to ethereum, and after this, it continues with the "create" button and keep working.

 think it also works if you eliminate that click but that code worked for me. It seems like the ethereum button is chose but is not, you can try it with an account without money in wallet to verify it.
