### ISSUE TITLE
Signature problem

### ISSUE THREAD

**Issue by Dennisman89** [nftdevs/NFTs-Upload-to-OpenSea#56]
Good day,

unfortunately It won’t sign automatically the sell now. Has anyone of you have a fix to this issue?

**Comment by WesyHub** [comment]
I have a solution, the software don't fnd the elements, you just need to replace by the new elements of the page.

Replace 
![image](https://user-images.githubusercontent.com/35263085/149624612-5931d1c7-34be-4565-a61f-2f54dbf10779.png)

wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
        sign = driver.find_element_by_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")

**Comment by cyborgz0x** [comment]
Worked for me, thanks!

**Comment by cyborgz0x** [comment]
> I have a solution, the software don't fnd the elements, you just need to replace by the new elements of the page.
> 
> Replace ![image](https://user-images.githubusercontent.com/35263085/149624612-5931d1c7-34be-4565-a61f-2f54dbf10779.png)
> 
> wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']") sign = driver.find_element_by_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")

Worked for me, thanks!

**Comment by uniteXander** [comment]
I think I am doing something wrong. I replaced line 193 as listed and I am still getting the  time out and the request for a signature. Any help would be appreciated!

**Comment by uniteXander** [comment]
Start creating NFT Sea Star #20
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\chapm\Desktop\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 193, in main_program_loop
    wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
  File "C:\Users\chapm\Desktop\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 119, in wait_css_selector
    wait.until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by WesyHub** [comment]
> I think I am doing something wrong. I replaced line 193 as listed and I am still getting the time out and the request for a signature. Any help would be appreciated!

Thats because you need to use dark mode of opensea.
My solution don't work with white mode.

**Comment by Cptnobeard** [comment]
> I have a solution, the software don't fnd the elements, you just need to replace by the new elements of the page.
> 
> Replace ![image](https://user-images.githubusercontent.com/35263085/149624612-5931d1c7-34be-4565-a61f-2f54dbf10779.png)
> 
> wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']") sign = driver.find_element_by_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")

Not sure whats going wrong here but im in dark mode on opensea and i replaced the line exactly like you said. 
still i have the following issue. 

Start creating NFT test #14
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 193, in main_program_loop
    wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb kCijbX']")
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 119, in wait_css_selector
    wait.until(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

![line](https://user-images.githubusercontent.com/99050474/152677529-79373a83-0865-4166-862c-d18382312e91.png)

**Comment by EnisGX** [comment]
set opensea on white theme
