### ISSUE TITLE
help wont upload nfts

### ISSUE THREAD

**Issue by billrod76** [nftdevs/NFTs-Upload-to-OpenSea#58]

**Comment by billrod76** [comment]
C:\Users\Bill9\Downloads\NFTs-Upload-to-OpenSea-nft76\NFTs-Upload-to-OpenSea-nft\openseaupload.py:111: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Bill9\Downloads\NFTs-Upload-to-OpenSea-nft76\NFTs-Upload-to-OpenSea-nft\openseaupload.py", line 111, in main_program_loop
    driver = webdriver.Chrome(
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 97.0.4692.71
What is this and how do i fix it?

**Comment by aetnix** [comment]
You have to install lastest chromedrive version from here https://chromedriver.chromium.org/downloads
