### ISSUE TITLE
Cant Log to OpenSea

### ISSUE THREAD

**Issue by gsciammarella** [nftdevs/NFTs-Upload-to-OpenSea#59]
I was uploading NFT's to Open Sea without any problem, until yesterday.
While my application was trying to connect to login to OpenSea I am get the error: 

Login to Opensea. C:\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py:359: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")Traceback (most recent call last):
  File "C:\Users\#\Documents\GitHub\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 578, in <module>
    opensea.opensea_login()  # Connect to Opensea.
  File "C:\Users\#\Documents\GitHub\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 266, in opensea_login
    if self.element_visible(
  File "C:\Users\#\Documents\GitHub\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 182, in element_visible
    return WDW(self.driver, timer).until(EC.visibility_of_element_located(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until    
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

Then I get stuck in that screen:

![image](https://user-images.githubusercontent.com/20301656/150262922-25d53a4d-1b47-4eff-92d9-dd51df8b8091.png)

Then I manually try to click to log into MetaMask and get the new screen:

![image](https://user-images.githubusercontent.com/20301656/150263133-e3c788cc-7f79-4838-b808-e6a4dce319d4.png)

But I have the extension, i dont really know how to solve this...

**Comment by gsciammarella** [comment]
For those who still have this isse the solution is here:
https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/issues/19

**Comment by Rbaviskar1** [comment]
> For those who still have this isse the solution is here: [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#19](https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/issues/19)

I can't seem to find the solution in the link. Can you please post it again maybe?
