### ISSUE TITLE
wont loop i have to upload 1 at a time. help please.

### ISSUE THREAD

**Issue by billrod76** [nftdevs/NFTs-Upload-to-OpenSea#61]
Start creating NFT BaseBunnies5
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Bill9\Downloads\NFTs-Upload-to-OpenSea-main (1)\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 164, in main_program_loop
    wait.until(ExpectedConditions.presence_of_element_located(
  File "C:\Users\Bill9\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

what does this mean?

**Comment by billrod76** [comment]
also how do i fix it?

**Comment by onerockdigital** [comment]
same

**Comment by ianhuang1** [comment]
same
