### ISSUE TITLE
Error when running script: No module named 'tkinter'

### ISSUE THREAD

**Issue by NMWijayasekara** [nftdevs/NFTs-Upload-to-OpenSea#63]
So I tried to run the script but I didn't work because tkinter as not install so I tried to install it manually but it also doesn't work.
`
line 1, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'
`

**Comment by sumair78692** [comment]
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "openseaupload.py", line 71, in <module>
    collection_link_input = InputField("OpenSea Collection Link:", 2, 0, 1)
  File "openseaupload.py", line 58, in __init__
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
