### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by nftbyart** [nftdevs/NFTs-Upload-to-OpenSea#69]
hello. 
I am on mac. Everything is working until i launch the chromedriver. I changed the chromedriver.exe by a chromedriver.unix and i changer the code in the opeanseaupload.py but it still does not work. If it is possible to get some Help... 

Have a nice day

**Comment by Bullet55NL** [comment]
I've got the same issue. Is it possible you can provide a Mac (m1) version for this ?

**Comment by mdaasim7oct2000** [comment]
I am also a mac user , i don't know much about coding and all , all things go well until i click open crome option, plzz solve the issue you rhe the only hope .thanks a lot for helping us all .

**Comment by JannieP** [comment]
i did a whole rework for mac, with additional resistance enhancements, I will be submitting a pull request. 
feel free to have a look at my fork

**Comment by nftbyart** [comment]
thank you for your work. Unfortunately, when i click to open chrome browser, it goes to that adresse : http://0.0.0.2/ . I tried to put the good URL into the python coad but it does not work. Do you know how to fix it ?

**Comment by nftbyart** [comment]
Here is the code of the problem : 

python3 openseaupload.py
[31795:60419:0127/094841.187225:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48)
[31795:60419:0127/094841.187365:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48)
[31795:60419:0127/094841.187401:ERROR:devtools_http_handler.cc(298)] Cannot start http server for devtools.
[31795:36355:0127/094843.349662:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[31795:36355:0127/094843.350434:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[31795:36355:0127/094843.350461:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328.
[31795:36355:0127/094843.350511:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()

**Comment by nftbyart** [comment]
Try: brew install selenium before everything if you have homebrew

**Comment by Cherokkee888** [comment]
> Try: brew install selenium before everything if you have homebrew

Yes, it was already installed. selenium and homebrew

**Comment by JannieP** [comment]
> thank you for your work. Unfortunately, when i click to open chrome browser, it goes to that adresse : http://0.0.0.2/ . I tried to put the good URL into the python coad but it does not work. Do you know how to fix it ?

That 0.0.0.2 is just a placeholder, 
If you want to make use of the AUTO login, you don't have to click the OpenBrowser, just add your MetaMask password then just click Start, it will still open to the 0.0.0.2, but it will auto switch to the correct window and start running.
And log you in, and start processing.
If you are not comfortable to capture your password, than that is OK too.

In that case just click the Open Browser, and manually open OpenSea, and the do a manual logging using your metamask plugin, then once logged in, just click the start button. The code will check if you are already logged in.

The reason I added the additional Metamask login code is because OpenSea has been experiencing lots of small outages in the last few weeks, which causes this process to fail, thus I updated it to attempt to auto login.
and continue.

I did however run into a new Oddity, where OpenSea added a daily upload limit, I am not sure exactly the number but you will see it on the screen

When that occurs, just wait till next day.

**Comment by JannieP** [comment]
> Here is the code of the problem :
> 
> python3 openseaupload.py [31795:60419:0127/094841.187225:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48) [31795:60419:0127/094841.187365:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48) [31795:60419:0127/094841.187401:ERROR:devtools_http_handler.cc(298)] Cannot start http server for devtools. [31795:36355:0127/094843.349662:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328. [31795:36355:0127/094843.350434:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability() [31795:36355:0127/094843.350461:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328. [31795:36355:0127/094843.350511:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()

You would need to either change the port in the code, or close the already running Process locking that port, it could be anything on your machine, thus I would go with changing the port in the code

**Comment by nftbyart** [comment]
thank you very much I just restarted to fix the problem of the process locking. Meanwhile, I had to add these options to the code : 

 options = webdriver.ChromeOptions()
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    options = webdriver.ChromeOptions()
    options.add_experimental_option('excludeSwitches', ['enable-logging'])

thank you very much

**Comment by nftbyart** [comment]
Do you have a version with metadata uploading? The version of nft devs don't access to opensea anymore. I think that it can be better with the manual access to opensea than run your code. That would be so great.

**Comment by JannieP** [comment]
> Do you have a version with metadata uploading? The version of nft devs don't access to opensea anymore. I think that it can be better with the manual access to opensea than run your code. That would be so great.

What do you mean by metadata are you thinking of?
are you meaning: properties, levels, and stats?

**Comment by BagelHole** [comment]
> > Do you have a version with metadata uploading? The version of nft devs don't access to opensea anymore. I think that it can be better with the manual access to opensea than run your code. That would be so great.
> 
> What do you mean by metadata are you thinking of? are you meaning: properties, levels, and stats?

Is there a version with uploading of properties, levels, and stats? I am curious how possible it is, I could try and code a solution.

**Comment by nftbyart** [comment]
https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata

Here is a version with metadata but it does not work when it needs to log in opensea. 
 That would be to add the properties of each nft. Do you think it is possible to add that to the code ? 
  I think It s easier if we log in manually to opensea like in that code.

**Comment by JannieP** [comment]
> > > Do you have a version with metadata uploading? The version of nft devs don't access to opensea anymore. I think that it can be better with the manual access to opensea than run your code. That would be so great.
> > 
> > 
> > What do you mean by metadata are you thinking of? are you meaning: properties, levels, and stats?
> 
> With properties yes

Nice, thanks, I will have a look and try add it as well

**Comment by JannieP** [comment]
> > > > Do you have a version with metadata uploading? The version of nft devs don't access to opensea anymore. I think that it can be better with the manual access to opensea than run your code. That would be so great.
> > > 
> > > 
> > > What do you mean by metadata are you thinking of? are you meaning: properties, levels, and stats?
> > 
> > 
> > With properties yes
> 
> Nice, thanks, I will have a look and try add it as well

Ok, sweet, this look like a possible solution, however, since likely most will be using the hashlips code to generate their images, I am going to see if I can use the hashlips json pattern to build the code, then add additional field for additional metadata. That way at least most of the json is autogenerated. I am a bit short on available time right now, but I will try my best

**Comment by sumair78692** [comment]
i have done everything as mentioned but still not working :


DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "openseaupload.py", line 71, in <module>
    collection_link_input = InputField("OpenSea Collection Link:", 2, 0, 1)
  File "openseaupload.py", line 58, in __init__
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
