### ISSUE TITLE
it stops at the metamask sign step

### ISSUE THREAD

**Issue by onerockdigital** [nftdevs/NFTs-Upload-to-OpenSea#73]
now i find a solution, it works now but only to the sign part on metamask? someone a solution for this?

**Comment by onerockdigital** [comment]
Start creating NFT #10
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Fred\Downloads\NFTs-Upload-to-OpenSea-main (2)\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 142, in main_program_loop
    wait_xpath('//*[@id="media"]')
  File "C:\Users\Fred\Downloads\NFTs-Upload-to-OpenSea-main (2)\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 129, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\Fred\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


this is the message

**Comment by cyborgz0x** [comment]
Same here...

**Comment by JohnnieW4lker** [comment]
Comment out these 4 lines of code:

![code](https://user-images.githubusercontent.com/50073222/152126761-21f1f256-a593-48c5-a0c4-3e1f76417fd8.png)

Opensea automatically opens metamask so code is getting stuck trying to press non-existing on-site sign button.
