### ISSUE TITLE
Won't upload any more than 1

### ISSUE THREAD

**Issue by NFTBlockchainWanderer** [nftdevs/NFTs-Upload-to-OpenSea#81]
When uploading to OpenSea, it will upload and list the first item, but when the splash screen appears to say that the item has been listed, nothing then happens and it crashes with the following:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\USER\Desktop\Upload\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 193, in main_program_loop
    wait_css_selector("button[class='Blockreact__Block-sc-1xf18x6-0 Buttonreact__StyledButton-sc-glfma3-0 bhqEJb fzwDgL']")
  File "C:\Users\USER\Desktop\Upload\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 119, in wait_css_selector
    wait.until(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

I don't have anything after this and I have to restart the program. ChromeDriver has been updated.

**Comment by thommycgn** [comment]
This happens because OpenSea is often really slow. If it tooks over 60 seconds you get this error. 

You can change line 115 to
`wait = WebDriverWait(driver, 240)`

This works well for me.
