### ISSUE TITLE
error when it arrives to polygon

### ISSUE THREAD

**Issue by alexl-11** [nftdevs/NFTs-Upload-to-OpenSea#82]
Traceback (most recent call last):
  File "D:\Users\alexl\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Users\alexl\Downloads\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 142, in main_program_loop
    wait_xpath('//*[@id="media"]')
  File "D:\Users\alexl\Downloads\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 129, in wait_xpath
    wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "D:\Users\alexl\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

how i can fix it?

**Comment by thommycgn** [comment]
You can change line 115 to
`wait = WebDriverWait(driver, 240)`
for higher the waiting time.

Polygon selectbox didn't work for me with this script. 
But commenting out line 160-168 worked well for me.

**Comment by iramalex11** [comment]
If you chose Polygon during the creation of the collection (before upload NFT's) is not necessary make the action of lines 160-168 because the polygon button is already chosen when you join the upload page. This is the solution:

`if is_polygon.get():
            blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]')
            blockchain_button.click()
            time.sleep(1)
            create = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button')
            driver.execute_script("arguments[0].click();", create)
            time.sleep(1)`

I stopped the code when it clicks on the blockchain button, but only makes a single click without changing to ethereum, and after this, it continues with the "create" button and keep working.

**Comment by iramalex11** [comment]
If you chose Polygon during the creation of the collection (before upload NFT's) is not necessary make the action of lines 160-168 because the polygon button is already chosen when you join the upload page. This is the solution:

`if is_polygon.get():
            blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]')
            blockchain_button.click()
            time.sleep(1)
            create = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button')
            driver.execute_script("arguments[0].click();", create)
            time.sleep(1)`

I stopped the code when it clicks on the blockchain button, but only makes a single click without changing to ethereum, and after this, it continues with the "create" button and keep working.

**Comment by iramalex11** [comment]
> If you chose Polygon during the creation of the collection (before upload NFT's) is not necessary make the action of lines 160-168 because the polygon button is already chosen when you join the upload page. This is the solution:
> 
> `if is_polygon.get(): blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]') blockchain_button.click() time.sleep(1) create = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button') driver.execute_script("arguments[0].click();", create) time.sleep(1)`
> 
> I stopped the code when it clicks on the blockchain button, but only makes a single click without changing to ethereum, and after this, it continues with the "create" button and keep working.

 think it also works if you eliminate that click but that code worked for me. It seems like the ethereum button is chose but is not, you can try it with an account without money in wallet to verify it.

**Comment by iramalex11** [comment]
If you chose Polygon during the creation of the collection (before upload NFT's) is NOT necessary make the action of lines 160-168 because the polygon button is already chosen when you join the upload page. This is the solution:

`if is_polygon.get():
            create = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/main/div/div/section/div[2]/form/div/div[1]/span/button')
            driver.execute_script("arguments[0].click();", create)
            time.sleep(1)`

Just eliminate the lines 161-168 and continue with the code (the condition of line 160 remains).
All this ONLY if you chose Polygon during the creation of the collection.
