### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by calvinvalerian** [nftdevs/NFTs-Upload-to-OpenSea#96]
![Screenshot (244)](https://user-images.githubusercontent.com/18316781/154236906-56eafe4e-1dbf-4483-9e00-5c5b8b5ba8ed.png)

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\calvi\OneDrive\Desktop\NFTs-Upload-to-OpenSea-main\openseaupload.py", line 134, in main_program_loop
    driver.get(collection_link)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\calvi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=98.0.4758.102)`

**I had installed the latest chromedriver from https://chromedriver.storage.googleapis.com/index.html?path=98.0.4758.102/**

**Comment by Amanullah5005** [comment]
I have also this eror

**Comment by MhanolloGhames** [comment]
Python 3.10.2:
---------------------------------------------------------------------------------------
1) pip => c:\Users\Mhanollo\AppData\Local\Programs\Python\Python310\Scripts
-> pip command line it´s here.
-> copy here all files related + Chrome WebDriver updated.
-> ..\python.exe -m pip install --upgrade pip
-> pip install tk
-> pip install selenium
-> pip install -U selenium
-> pip install selenium --upgrade
-> pip show selenium
-> pip install  pillow
-> pip install certifi
-> pip install python-dateutil
-> pip install -r requirements.txt
-> pip install chromedriver-autoinstaller
-> pip install python-dateutil
-> npm install
-> npm update
-> npm install chromedriver -g
-> ..\python.exe openseaupload.py

**Comment by calvinvalerian** [comment]
I use alternative software I will close this issue
